configMapGenerator:
  - files:
      - application.yml
    name: 82265604-configmap
resources:
  - ../../base
  - pvc.yaml
patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
  - name: ceappacr.azurecr.io/82265604
    newTag: "202411041110"